# Generated by Django 3.2.4 on 2021-06-07 23:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20210607_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_logo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
