# Generated by Django 3.2.4 on 2021-06-08 09:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20210607_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dfgpy7csp/image/upload/v1623137444/images/default.jpg', max_length=255, null=True, verbose_name='images'),
        ),
    ]
